# Generated by Django 5.1.4 on 2025-01-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я отримувача")),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамілія отримувача')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону отримувача')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='orders.order')),
            ],
            options={
                'verbose_name': 'Отримувач',
                'verbose_name_plural': 'Отримувачі',
            },
        ),
    ]
