# Generated by Django 5.1.4 on 2025-01-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='ref_warehouse',
            field=models.CharField(default='Подзвонити для уточнення', max_length=120, verbose_name='Відділення почти'),
        ),
    ]
