# Generated by Django 5.1.4 on 2025-01-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_alter_category_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Назва магазину')),
                ('email', models.EmailField(max_length=100, verbose_name='Емейл')),
                ('phone', models.CharField(max_length=14, verbose_name='Номер телефону')),
                ('adress', models.CharField(max_length=150, verbose_name='Адресса')),
                ('social_media', models.JSONField(verbose_name='Соціальні мережі')),
                ('work_span', models.JSONField(verbose_name='Графік роботи')),
                ('descriptions', models.TextField(verbose_name='Опис магазину')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.image', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Інформація про магазин',
                'verbose_name_plural': 'Інформація про магазин',
            },
        ),
    ]
