# Generated by Django 5.1.4 on 2025-01-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_name_category_name_uk_category_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_uk',
            new_name='name',
        ),
    ]
