# Generated by Django 5.1.4 on 2025-01-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_name_uk_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Назва англійською'),
        ),
    ]
