# Generated by Django 5.1.4 on 2025-01-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Назва англійською'),
        ),
    ]
